<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create Account_tel</name>
   <tag></tag>
   <elementGuidId>5f0ed0a1-df96-4853-9f1e-d1ee3cedc769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputTel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputTel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87d6bda1-2fcd-4272-b6cf-008de63a92c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cbeecd29-30f3-40b4-aeca-429e6009e8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>61dfb047-b817-4027-8a0b-dc297551d3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputTel</value>
      <webElementGuid>cc9dbb2d-5366-45f8-8657-17a3a92fbf8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>1dbdd8d2-e711-475a-a3a7-741d9ac29430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tel</value>
      <webElementGuid>0d71b612-5b0f-492a-b12f-3944e8956797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputTel&quot;)</value>
      <webElementGuid>ebc7c00f-88b7-4b17-984a-2804d38c4595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputTel']</value>
      <webElementGuid>28a1a45f-e8f4-49b4-a441-b1a3bd523fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>3cf73bde-b110-49fb-9487-1e81f89d9ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputTel' and @name = 'tel' and @placeholder = 'Tel']</value>
      <webElementGuid>e08017a8-84c7-4133-a5a1-3ae79b99b480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
