<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create Account_username</name>
   <tag></tag>
   <elementGuidId>51daa5d7-f54e-46f0-aafb-199e338a8e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputUsername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputUsername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6f2a829-8b1a-4ecf-92ae-f5debcf18708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23afd1aa-888a-4c30-a89b-c1b356acf8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e8a99f5d-c0a9-4583-905f-158595b158c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputUsername</value>
      <webElementGuid>86f344ae-0a6a-440b-87d5-b743665b6aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>68193104-0da6-43b4-8492-a769959c72f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>c7bd1ec7-2b7d-4218-98a2-412c13646920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputUsername&quot;)</value>
      <webElementGuid>45e7e4fd-7237-455a-a9d5-6646fdc39668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputUsername']</value>
      <webElementGuid>db0dda28-a650-4eb0-ad84-b4d6a6b872d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>b5d7fe44-6010-401f-8ecd-06cd029ca5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputUsername' and @name = 'username' and @placeholder = 'Username']</value>
      <webElementGuid>c2bfdbf6-197a-4f26-94cd-7eabe67030c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
