<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_12312312324</name>
   <tag></tag>
   <elementGuidId>2f733847-ff14-4a0e-b7a2-ad4f7ac08ba0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='content']/tr/th/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.link-page</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a993b366-33e0-4058-aea5-042d02342d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-page</value>
      <webElementGuid>fc70f147-4550-4039-8321-84e892cf3a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>DetailStat?edate=2021-12-01&amp;sdate=2021-10-22&amp;name=macbook pro 2021&amp;pid=1</value>
      <webElementGuid>f286b4a3-159a-441a-8b00-ea2f072dcb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12312312324</value>
      <webElementGuid>912ff9c7-2e94-443d-a32f-d92dbb4ee5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/tr[1]/th[1]/a[@class=&quot;link-page&quot;]</value>
      <webElementGuid>1d11e1e9-fb1f-4728-8e1f-7b1f7f2750ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='content']/tr/th/a</value>
      <webElementGuid>b1c63e8a-aaf3-4f51-93a0-92c217c95b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'12312312324')]</value>
      <webElementGuid>645e77f4-fc1a-4f29-9243-57ded0d88098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::a[1]</value>
      <webElementGuid>3860ca6c-fdf1-4a26-9606-b0e27f5e111a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sold Quantity'])[1]/following::a[1]</value>
      <webElementGuid>b12eea83-d80b-43b8-b9c4-5e13d62661c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='macbook pro 2021'])[2]/preceding::a[1]</value>
      <webElementGuid>bda19974-51d8-4eba-94ce-2c4d291b1e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2001.98'])[1]/preceding::a[1]</value>
      <webElementGuid>f8573abb-776b-4f81-8325-392e2efa21d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12312312324']/parent::*</value>
      <webElementGuid>52acb156-8946-4c5c-96e6-75b81228c977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'DetailStat?edate=2021-12-01&amp;sdate=2021-10-22&amp;name=macbook pro 2021&amp;pid=1')]</value>
      <webElementGuid>e414555d-6573-4233-8507-1eb5f95d1a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/a</value>
      <webElementGuid>4c008ebd-a616-42c5-9422-56af67a969d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'DetailStat?edate=2021-12-01&amp;sdate=2021-10-22&amp;name=macbook pro 2021&amp;pid=1' and (text() = '12312312324' or . = '12312312324')]</value>
      <webElementGuid>0be7de74-a947-4f48-a951-635d5853b1b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
